<?php
    if(!isset($bien_bao_mat)){exit();}// xuất ra trang trắng nếu truy cập trực tiếp vào file này mà không đăng nhập
?>
<?php
    //xác định biểu mẫu thêm menu ngang có được gửi hay không nếu được gửi thì sẽ tồn tại biến $_POST['bieu_mau_them_menu_ngang'] 
    if(isset($_POST['bieu_mau_them_menu_ngang']))
    {    // file này có chức năng thêm menu ngang vào bảng 'menu_ngang'
        include("chucnang/menungang/them_menu_ngang_vao_csdl.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieu_mau_sua_menu_ngang']))
    {
        include("chucnang/menungang/sua_menu_ngang_o_trong_csdl.php");
        trang_truoc_html();
    }
    if(isset($_GET['xoa_menu_ngang']))
    {
        include("chucnang/menungang/xoa_menu_ngang.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieu_mau_them_menu_doc']))
    {
        include("chucnang/menudoc/them_menu_doc_vao_csdl.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieu_mau_sua_menu_doc']))
    {
        include("chucnang/menudoc/sua_menu_doc_o_trong_csdl.php");
        trang_truoc_html();
    }
    if(isset($_GET['xoa_menu_doc']))
    {
        include("chucnang/menudoc/xoa_menu_doc.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieu_mau_them_san_pham']))
    {
        include("chucnang/sanpham/them_san_pham_vao_csdl.php");
        trang_truoc_html();
    }
    
    if(isset($_POST['bieu_mau_them_so_luong_san_pham']))
    {
        include("chucnang/sanpham/them_so_luong_san_pham_vao_csdl.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieu_mau_sua_san_pham']))
    {
        include("chucnang/sanpham/sua_san_pham_o_trong_csdl.php");
        trang_truoc_html();
    }
    if(isset($_GET['xoa_san_pham']))
    {
        include("chucnang/sanpham/xoa_san_pham.php");
        trang_truoc_html();
    }
    if(isset($_GET['xoa_hoa_don']))
    {
        include("chucnang/hoadon/xoa_hoa_don.php");
        trang_truoc_html();
    }
    if(isset($_GET['xoa_hoa_don2']))
    {
        include("chucnang/hoadon/xoa_hoa_don2.php");
        trang_truoc_html();
    }
    if(isset($_GET['xoa_hoa_don3']))
    {
        include("chucnang/hoadon/xoa_hoa_don3.php");
        trang_truoc_html();
    }
    if(isset($_GET['xoa_hoa_don4']))
    {
        include("chucnang/hoadon/xoa_hoa_don4.php");
        trang_truoc_html();
    }
    if(isset($_GET['xoa_chi_tiet_don_hang']))
    {
        include("chucnang/hoadon/xoa_chi_tiet_hoa_don.php");
        trang_truoc_html();
    }
    if(isset($_GET['duyet_hoa_don']))
    {
        include("chucnang/hoadon/duyet_hoa_don.php");
        trang_truoc_html();
    }
    if(isset($_GET['duyet_hoa_don2']))
    {
        include("chucnang/hoadon/duyet_hoa_don_hoan_thanh.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieu_mau_them_nhan_vien']))
    {
        include("chucnang/nhanvien/them_thong_tin_nhan_vien_vao_csdl.php");
        trang_truoc_html();
    }
    
    if(isset($_POST['bieu_mau_sua_thong_tin_nhan_vien']))
    {
        include("chucnang/nhanvien/sua_thong_tin_nhan_vien_trong_csdl.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieu_mau_xoa_nhan_vien']))
    {
        include("chucnang/nhanvien/xoa_nhan_vien_trong_csdl.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieu_mau_san_pham_trang_chu']))
    {
        include("chucnang/sanphamtrangchu/sua_san_pham_trang_chu.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieu_mau_san_pham_noi_bat']))
    {
        include("chucnang/sanphamnoibat/sua_san_pham_noi_bat.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieu_mau_them_slideshow']))
    {
        include("chucnang/slideshow/them_slideshow_vao_csdl.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieu_mau_sua_slideshow']))
    {
        include("chucnang/slideshow/sua_slideshow_o_trong_csdl.php");
        trang_truoc_html();
    }
    if(isset($_GET['xoa_slideshow']))
    {
        include("chucnang/slideshow/xoa_slideshow.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieu_mau_sua_footer']))
    {
        include("chucnang/footer/sua_footer_o_trong_csdl.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieu_mau_them_quang_cao_trai']))
    {
        include("chucnang/quangcaotrai/them_quang_cao_trai_vao_csdl.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieu_mau_sua_quang_cao_trai']))
    {
        include("chucnang/quangcaotrai/sua_quang_cao_trai_o_trong_csdl.php");
        trang_truoc_html();
    }
    if(isset($_GET['xoa_quang_cao_trai']))
    {
        include("chucnang/quangcaotrai/xoa_quang_cao_trai.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieu_mau_them_quang_cao_phai']))
    {
        include("chucnang/quangcaophai/them_quang_cao_phai_vao_csdl.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieu_mau_sua_quang_cao_phai']))
    {
        include("chucnang/quangcaophai/sua_quang_cao_phai_o_trong_csdl.php");
        trang_truoc_html();
    }
    if(isset($_GET['xoa_quang_cao_phai']))
    {
        include("chucnang/quangcaophai/xoa_quang_cao_phai.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieu_mau_sua_thong_tin_quan_tri']))
    {
        include("chucnang/quantri2/sua_thong_tin_quan_tri_o_trong_csdl.php");
        trang_truoc_html();
    }   
    if(isset($_GET['thamso']))
    {
        if($_GET['thamso']=="thoat")
        {
            include("chucnang/quantri2/thoat.php");
            trang_truoc_html();
        }
    }
?>